### PR TITLE
Events data removed from payload

### LINKED ISSUE #198: Refactor plugins to use new transistor event interface
Transistor's event interface is changing soon. Update the plugins / message transceivers to handle new interface.

https://github.com/codeamp/transistor/issues/17

### PR DESCRIPTION
**Pull request by aballman**
This is a pretty heavy change.

Please review:
* Github Status plugin
* Mutation.go
* CodeAmp Plugin

Still yet to do:
* Adjust the ORM model for removed fields (state/statemessage)
* Adjust the seed data to not include removed fields
* Another pass of updating NewEvent calls to use transistor's event.Create() / event.Status() / etc.
* Update vendor folder for latest transistor edits  (could be done as part of https://github.com/codeamp/circuit/issues/194)

Fixes #198

### CODE REVIEW

**Comment by aballman** [comment]
I still need to update the names of the events subscriptions in some places.

**Comment by sasso** [comment]
Can you also resolve the conflicts before I start my review

**Comment by aballman** [comment]
@sasso You got ahead of me, you speedy man, you. Working on it.

**Comment by sasso** [comment]
and --rebase because I think we already merged LOG_LEVEL :)

**Comment by aballman** [comment]
@sasso
https://github.com/codeamp/circuit/blob/91b96f9d774ec88716be78f8d204427efb0b843d/plugins/codeamp/codeamp.go#L183

It looks like the codeamp plugin receives messages, and then using reflection tries to hand it off to a handler on the payload.

Why doesn't that go through the normal message bus as opposed to having codeamp be a secondary handler for events?

**Comment by sasso** [comment]
We were playing with different options of responding to events. The process became really big and hard to manage so we broke it down to methods. We could also go back to the standard way or have a switch case that calls methods...

**Pull request merged**
